projects:
  theplayerscompany:
    # schemaPath: amplify/backend/api/theplayerscompany/build/schema.graphql
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 6
extensions:
  amplify:
    version: 3
